### ISSUE TITLE
August 16, 2022 Meeting

### ISSUE THREAD

**Issue by dotnetdc** [dotnetdc/Open-Governance#12]
![DotNetDC Event August 16 2022 Event Sourcing and CQRS with Marten](https://user-images.githubusercontent.com/2148318/182704997-f894427f-8f11-4c93-8f92-49153f5a3cd4.png)

## Links

* Meetup: https://www.meetup.com/dotnetdc/events/287448528/
* .NET Foundation Virtual Meetup: https://www.meetup.com/dotnet-virtual-user-group/events/287602503/
* .NET DC YouTube: https://www.youtube.com/watch?v=XaztVpahD1k
* LinkedIn: https://www.linkedin.com/video/event/urn:li:ugcPost:6958092988027691008/
* Twitch: https://www.twitch.tv/sjkilleen

## Speaker 

Jeremy Miller (@jeremydmiller)

## Topic 

Event Sourcing and CQRS with Marten

## Abstract

Marten (https://martendb.io/) is an open source library that enables .Net developers to use the rock solid Postgresql database as a full featured event store and document database. In this session I'll show how Marten provides "event sourcing in a box" through its integrated support for capturing event streams, projecting "read-side" views of those same event streams, and full support for storing and querying the projected views. All with one library and database.

We'll start with an obligatory quick start, but move into how to scale an event sourced application with Marten to very large data sets.

In a conference dedicated to event sourcing, we'll go beyond the basics of event sourcing into Marten's unique abilities like live aggregation and "inline" projections when you need ACID compliance rather than eventual consistency. We'll also look at how Marten helps you deal with concurrency issues during event sourcing.

## Bio

Jeremy Miller is the Senior Director of Software Architecture at MedeAnalytics. Jeremy began his software career writing "Shadow IT" applications to automate his tedious engineering documentation, then wandered into software development because it looked like more fun. Jeremy is heavily involved in open source .NET development as the the lead developer of Marten, Lamar, Alba, and other projects in the JasperFx family. Jeremy occasionally manages to write about various software topics at http://jeremydmiller.com/.

Pic: https://avatars.githubusercontent.com/u/179211?v=4

## Before Meeting

* [x] Source speaker
* [x] Capture topic here
* [x] Add preferred bio picture
* [x] Update/Add Meetup event
* [x] Announce meetup to group
* [x] Tweet from .NET DC Twitter account
* [x] Re-tweet from personal accounts
* [ ] Schedule Reminders
  * [ ] dotnetdc tweets (A few days before, day before, just before)
  * [ ] sean tweets (A few days before, day before, just before)
  * [ ] LinkedIn messages advertising the LinkedIn event (Buffer)
* [x] Submit [form for .NET Virtual User Group](https://dotnetfoundation.org/community/virtual-user-group)
  * [x] Add blurb `This session is part of the .NET Virtual User Group(https://www.meetup.com/dotnet-virtual-user-group) series, where you can join and find more virtual user groups happening around the world.`
  * [x] Add [Virtual group slides](https://github.com/dotnet-foundation/wg-outreach/raw/master/virtual_meetup/Virtual.User.Group.Slides.pptx) to intro deck
  * [x] Add Virtual User Group link to Speaker e-mail 
* [x] Create a StreamYard event meeting/link
* [x] Add a viewing link to Meetup
* [x] Prep slide deck
* [x] Add to Excella calendar for promotion
* [x] Submit request to Excella social media for banner
* [x] Invite speaker to Meeting with StreamYard guest link
* [x] Add stream destination to .NET DC User Group YouTube
* [x] Update links to .NET DC Meetup YouTube channel
* [x] Prep icebreakers / polleverywhere polls
* [x] Upload banner images
  * [x] YouTube
  * [x] LinkedIn
  * [x] Meetup - .NET DC
  * [x] Meetup - .NET Virtual User Group
* [x] Send connection request to Speaker on LinkedIn
  * [x] Add speaker to LinkedIn event (if connected)
* [ ] Publish the meetup in various channels
  * [x] DCTech Slack
  * [x] Rands Leadership Slack
  * [x] .NET Slack 
  * [ ] Discords
* [x] Add Jeremy to speaker e-mail once I get his preferred e-mail address.

**Comment by jeremydmiller** [comment]
# Event Sourcing and CQRS with Marten

For the speaker bio picture, can you just take the GitHub avatar?

https://twitter.com/jeremydmiller
https://jeremydmiller.com
Linked In: https://www.linkedin.com/in/jeremy-miller-500a3a1/
Email: shadetreedeveloper@gmail.com


## Abstract:

Marten (https://martendb.io/) is an open source library that enables .Net developers to use the rock solid Postgresql database as a full featured event store and document database. In this session I'll show how Marten provides "event sourcing in a box" through its integrated support for capturing event streams, projecting "read-side" views of those same event streams, and full support for storing and querying the projected views. All with one library and database.

We'll start with an obligatory quick start, but move into how to scale an event sourced application with Marten to very large data sets.

In a conference dedicated to event sourcing, we'll go beyond the basics of event sourcing into Marten's unique abilities like live aggregation and "inline" projections when you need ACID compliance rather than eventual consistency. We'll also look at how Marten helps you deal with concurrency issues during event sourcing.



## Bio:

Jeremy Miller is the Senior Director of Software Architecture at MedeAnalytics. Jeremy began his software career writing "Shadow IT" applications to automate his tedious engineering documentation, then wandered into software development because it looked like more fun. Jeremy is heavily involved in open source .NET development as the the lead developer of Marten, Lamar, Alba, and other projects in the JasperFx family. Jeremy occasionally manages to write about various software topics at http://jeremydmiller.com/.
